# Generated by Django 5.2.4 on 2025-07-16 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='name',
        ),
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='ingredient',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='status',
            field=models.CharField(blank=True, help_text='active | inactive | entered-in-error', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
